name: Metrics
on:
  # Runs every 6 hours
  schedule: [{cron: "*/360 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ithelor
          base: header, activity, community, repositories
          config_display: regular
          config_padding: 0, 8 + 11%
          config_timezone: Asia/Vladivostok
          plugin_isocalendar: yes
          plugin_isocalendar_duration: year
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 1.0
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_limit: 5
          plugin_achievements: yes