name: Metrics
on:
  # Runs at hour 0, 6, 12 and 18
  schedule: [{cron: "0 0,6,12,18 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ithelor
          base: no
          config_display: regular
          config_padding: 0, 8 + 11%
          config_timezone: Asia/Vladivostok
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_skyline: no
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1.0
          plugin_wakatime: no
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_limit: 5
          plugin_achievements: yes