name: Metrics
on:
  # Runs every 6 hours
  schedule: [{cron: "*/360 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: ithelor
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: regular
          config_padding: 0, 8 + 11%
          config_timezone: Asia/Vladivostok
          plugin_achievements: no
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: no
          plugin_followup_sections: repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: year
          plugin_languages: yes
          plugin_languages_skipped: DiseaseAnalysisTool,TimezoneConverter,wp
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 28
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_pagespeed: no
          plugin_pagespeed_url: .user.website
          plugin_stars: yes
          plugin_stars_limit: 8